// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/domain-trees/Domain1AGraph.tsx": () => import("../components/mockups/domain-trees/Domain1AGraph.tsx"),
  "./components/mockups/domain-trees/Domain1ATree.tsx": () => import("../components/mockups/domain-trees/Domain1ATree.tsx"),
  "./components/mockups/domain-trees/Domain1BGraph.tsx": () => import("../components/mockups/domain-trees/Domain1BGraph.tsx"),
  "./components/mockups/domain-trees/Domain1BTree.tsx": () => import("../components/mockups/domain-trees/Domain1BTree.tsx")
};
